FROM node:16.14.2 as BUILDER

WORKDIR /app

COPY . .

RUN npm set cache ./.npm
RUN --mount=type=cache,target=/usr/src/app/.npm npm install --legacy-peer-deps
RUN --mount=type=cache,target=/usr/src/app/.npm npm install -g @angular/cli

RUN ng build

FROM nginx:1.23.1-alpine

WORKDIR /app

COPY --from=BUILDER /app/dist/vendas ./vendas
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
