FROM node:16.14.2 as BUILDER

WORKDIR /app

COPY . .

RUN npm install -g @angular/cli
RUN npm install --legacy-peer-deps
RUN ng build

FROM nginx:1.23.1-alpine

WORKDIR /app

COPY --from=BUILDER /app/dist/vendas ./vendas
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
